// Generated by scripts/commercial-copy-build.mjs. Do not edit.
import { commercialCopyContract } from "./contract";
import type { CommercialCopyRecord } from "./types";

export const commercialAdapterPageKeys = ["homepage","services-overview","pricing","work-evidence","contact","start","emergency","service-local-visibility","service-websites-hosting","service-provider-rescue","service-custom-tools","service-research-analytics"] as const;
export type CommercialAdapterPageKey = (typeof commercialAdapterPageKeys)[number];
const blockedSlotKeys = new Set<string>(["product.bohoAnalytics.publicFreeAvailability"]);

export function assertCommercialSlotAvailable(slotKey: string): void {
  if (blockedSlotKeys.has(slotKey)) throw new Error(`blocked commercial-copy slot requested: ${slotKey}`);
}

export function getCommercialPageAdapter(pageKey: CommercialAdapterPageKey): ReadonlyArray<CommercialCopyRecord> {
  return commercialCopyContract.records.filter((record) => record.pageKey === pageKey);
}

export const homepageCommercialAdapter = () => getCommercialPageAdapter("homepage");
export const servicesOverviewCommercialAdapter = () => getCommercialPageAdapter("services-overview");
export const pricingCommercialAdapter = () => getCommercialPageAdapter("pricing");
export const workEvidenceCommercialAdapter = () => getCommercialPageAdapter("work-evidence");
export const contactCommercialAdapter = () => getCommercialPageAdapter("contact");
export const startCommercialAdapter = () => getCommercialPageAdapter("start");
export const emergencyCommercialAdapter = () => getCommercialPageAdapter("emergency");
export const serviceLocalVisibilityCommercialAdapter = () => getCommercialPageAdapter("service-local-visibility");
export const serviceWebsitesHostingCommercialAdapter = () => getCommercialPageAdapter("service-websites-hosting");
export const serviceProviderRescueCommercialAdapter = () => getCommercialPageAdapter("service-provider-rescue");
export const serviceCustomToolsCommercialAdapter = () => getCommercialPageAdapter("service-custom-tools");
export const serviceResearchAnalyticsCommercialAdapter = () => getCommercialPageAdapter("service-research-analytics");
