/**
 * Reviewed, term-specific examples for glossary detail pages.
 *
 * Keep this keyed by the permanent glossary slug. The route validator enforces
 * exact parity with the canonical glossary registry so no page can fall back to
 * generic generated copy.
 */
export const glossaryPracticalExamples: Readonly<Record<string, string>> = Object.freeze({
  server: "A small business website might use a managed server platform that stores the built site, answers browser requests, records operational errors, and exposes a controlled deployment path without requiring the owner to maintain physical hardware.",
  "web-server": "When a visitor requests `/services/`, the web server can return a prepared HTML file immediately or pass the request to application code that assembles the response from templates and data.",
  client: "A browser is the client when it requests a webpage, while an analytics script can become a client of an event endpoint when it sends an approved measurement request.",
  browser: "A navigation menu that works in one desktop browser should also be checked in mobile Safari, Firefox, keyboard-only use, zoomed layouts, and screen-reader navigation because each browser environment can expose different failures.",
  "domain-name": "A business can keep its domain registration in an owner-controlled registrar account while pointing DNS records to a separately managed website host and email provider.",
  dns: "During a website migration, the web record may change while MX and email-verification records remain untouched; copying only the visible website setting could interrupt mail.",
  nameserver: "If a registrar changes authoritative nameservers from one DNS provider to another, the complete zone must exist at the new provider before the switch.",
  "dns-record": "An A record might direct the apex domain to a hosting service, an MX record route mail to a workspace provider, and a TXT record prove control to a search or email service.",
  hosting: "A static marketing site may fit a low-cost Pages platform, while a customer portal with accounts and private records needs a hosting model that also covers application execution, data storage, backups, and access controls.",
  "static-site": "A service company can publish fast, prebuilt service and glossary pages while sending contact forms to a separately governed endpoint; the public pages remain static even though the form workflow is dynamic.",
  cdn: "After a new logo is deployed, a CDN edge may continue serving the cached prior file until its cache key changes, it expires, or an authorized purge reaches that edge.",
  http: "A successful page request should return `200`, an old permanent URL should return `301` with its final destination, and a missing resource should return `404` rather than a visually styled error page with a success status.",
  tls: "When a customer opens an HTTPS form, TLS protects the submission while it travels to the intended host, but the form handler still needs secure validation, storage, retention, and access rules.",
  url: "Changing `/web-design` to `/services/web-design-redesign/` creates a new URL even on the same domain, so the old path needs a direct migration decision and any internal links should use the new canonical address.",
  redirect: "If an old analytics article moves into a glossary, a direct `301` from the exact historical article URL to the matching term page is more useful than sending the visitor through a hub or homepage.",
  "responsive-design": "A three-column service comparison can collapse into one readable column on a phone while retaining the same headings, decision information, focus order, and actions.",
  git: "Before revising pricing copy, a developer can create a branch, record the exact approved changes in a commit, compare them with the prior version, and restore the earlier source if review finds a problem.",
  github: "A business can own a GitHub organization containing its website repository, require pull-request review on `main`, run validation with Actions, and keep hosting credentials outside the repository.",
  repository: "A website repository can contain page components, content records, tests, build instructions, and revision history while the generated production files live on a separate hosting platform.",
  branch: "A glossary expansion can live on a review branch until every generated page passes content and crawl checks, leaving the production branch unchanged during editorial review.",
  commit: "A release record can name one commit so reviewers, CI, the preview, and the deployment all refer to exactly the same source rather than a moving folder of files.",
  deployment: "A production deployment can build a validated commit, upload its static artifact, receive an immutable preview URL, switch the approved version live, and preserve the prior deployment for rollback.",
  "ci-cd": "A pull request can automatically typecheck the site, build every static route, test canonicals and links, crawl redirects, and prevent merge when one generated glossary page is missing.",
  api: "A reporting integration might request conversion totals from an analytics API using a documented date range, property, metric definition, and read-only credential rather than copying a dashboard by hand.",
  "api-key": "A browser-safe maps key may be restricted to approved domains and APIs, while an administrative key belongs only in a protected server environment with narrower access and rotation procedures.",
  oauth: "A client can approve read-only Search Console access for an application, review the requested scope, revoke the token later, and keep the account password private.",
  "environment-variable": "A deployment can receive an analytics property identifier through its environment configuration so preview and production use the correct setting without embedding a private credential in source.",
  webhook: "A form service can send a signed webhook after a valid submission; the receiving workflow verifies the signature, handles retries idempotently, and avoids placing the message body in broad logs.",
  json: "A route audit expressed as JSON can give every URL the same fields for status, canonical, sitemap membership, and disposition, allowing tests to compare records deterministically.",
  automation: "A nightly check can crawl a site's sitemap, report broken internal links, and open a review item while leaving consequential fixes and deployment decisions for an authorized person.",
  mcp: "An MCP host can connect separate servers for approved repository reads, analytics reports, and controlled publishing while presenting each server's tools and permissions through a consistent protocol.",
  "mcp-server": "A narrow analytics MCP server might expose only predefined aggregate reports, never raw visitor records or account administration, and validate every requested date range.",
  "mcp-client": "The host's MCP client can connect to a repository server, list its declared tools, send one validated request, and return the structured result to the user interface.",
  "mcp-tool": "A `validate_redirects` tool could accept a governed route map, reject chains and loops, and return a bounded report without gaining permission to deploy the site.",
  "mcp-resource": "A server can expose an approved glossary specification as a read-only MCP resource so an agent can consult it without receiving arbitrary filesystem access.",
  "web-crawling": "A release crawler can begin with the sitemap, follow internal links, record status and canonical signals, and verify that every intended public glossary page is reachable without executing a search query.",
  crawler: "A search crawler and a local QA crawler may request the same page for different purposes; both should receive meaningful HTML, a correct status, and consistent canonical information.",
  "robots-txt": "A public site can allow crawling generally, identify its XML sitemap, and keep private systems protected through authentication rather than relying on robots.txt as an access control.",
  "xml-sitemap": "A generated sitemap can list each canonical glossary detail URL exactly once while excluding old redirect sources, fragments, and internal preview routes.",
  indexing: "After a new glossary URL becomes crawlable and indexable, a search engine may still choose when to crawl it, whether to include it, and which canonical representation to retain.",
  "google-analytics": "A site can record an approved form-success event in GA4 while excluding names, email addresses, message text, and other direct personal data from event parameters.",
  event: "A `contact_form_success` event should fire only after the endpoint confirms success, carry a documented non-personal context value, and avoid duplicate firing on refresh.",
  conversion: "For a service website, an accepted qualified inquiry may be a conversion, while a page view or button click can remain a diagnostic interaction rather than the business outcome.",
  "google-search-console": "Search Console can show that a glossary URL received impressions for a query, while the website's own analytics separately shows what happened after a visitor arrived.",
  "google-business-profile": "A local contractor can maintain accurate categories, hours, service information, and an owner-controlled website link in its Business Profile while treating the profile as separate from the website.",
  seo: "Improving a service page can involve clarifying the customer question, strengthening useful evidence, fixing crawl and canonical problems, and earning relevant references rather than repeating a target phrase.",
  "local-seo": "A local retailer can align its website location details, Business Profile, major citations, review process, and locally relevant pages without manufacturing near-duplicate city pages.",
  "technical-seo": "A migration review can find redirect chains, duplicate canonicals, missing sitemap URLs, accidental noindex tags, or JavaScript-only content before those issues interfere with discovery.",
  analytics: "A monthly review can combine qualified inquiries, source context, conversion definitions, and known tracking gaps so the team chooses an action instead of celebrating traffic alone.",
  metadata: "A glossary page can provide a unique title, preview-derived description, self-canonical, Open Graph fields, and visible content that all describe the same term.",
  "canonical-url": "If tracking parameters create several request URLs for one article, each version can reference the clean article URL as canonical while internal links use that canonical directly.",
  "structured-data": "A glossary detail page can mark its visible term and definition as `DefinedTerm` and its visible navigation trail as `BreadcrumbList` without claiming reviews, authorship, or results that the page does not show.",
  cms: "A marketing team might edit service copy in a CMS while developers maintain templates and deployment controls; ownership planning should cover both the content database and the rendering code.",
  cache: "A browser may reuse a versioned stylesheet for months while the HTML remains short-lived; changing the stylesheet filename on build lets old and new pages receive the correct asset.",
  "website-clarity": "A visitor landing on a provider-rescue page should quickly understand the problem addressed, what the engagement includes, what evidence exists, and how to start without decoding internal jargon.",
  "trust-signal": "A named process, accurate ownership boundary, inspectable work sample, and consistent contact information are stronger trust signals than an unsupported badge or vague superlative.",
  "customer-discovery": "A homeowner may discover a contractor in maps, compare service pages and reviews, return through a branded search, and finally call; the path spans several discovery surfaces.",
  "customer-action": "Downloading a checklist may show interest, but submitting a complete project inquiry or booking an approved consultation is closer to a decision-bearing customer action.",
  "call-to-action": "A service page can use “Request a technical review” when that accurately describes the next step, destination, and commitment instead of a vague “Learn more” button.",
  "search-intent": "Someone searching “what is a canonical URL” usually needs an explanation, while someone searching “technical SEO audit service” is evaluating a provider; the pages should serve those different tasks.",
  keyword: "A useful page about website redirects may naturally use terms such as permanent redirect, 301, old URL, migration, and redirect chain because those concepts help explain the subject.",
  "domain-registrar": "The business can keep registrar ownership, recovery email, renewal, and transfer controls in its own account while granting a provider only the access needed for a documented DNS change.",
  "website-backup": "Before a CMS update, a team can verify that both files and the database are backed up, record the restore procedure, and test recovery in a non-production environment.",
  "ssl-certificate": "A hosting platform may automatically issue and renew certificates for the apex and `www` hostnames, but monitoring should still detect an expired, mismatched, or missing hostname certificate.",
  "dynamic-website": "A customer portal may render account-specific records after authentication, while its public marketing and glossary pages can still be delivered as static files.",
  html: "A glossary page can use one `h1`, labeled navigation, real paragraphs, lists, and ordinary links so browsers, assistive technology, and crawlers receive meaningful document structure.",
  "web-form": "A project inquiry form can label every field, explain sensitive-data limits, validate required values, provide keyboard-visible errors, and show success only after the endpoint accepts the submission.",
  accessibility: "A menu should remain understandable with semantic landmarks, keyboard navigation, visible focus, sufficient contrast, zoomed text, and screen-reader labels rather than relying on pointer hover.",
  "web-performance": "Replacing a multi-megabyte hero with an appropriately sized compressed image can improve the largest-contentful render while preserving a useful visual and alternative text.",
  "internal-link": "A glossary hub can link “Canonical URL” directly to its dedicated definition page, while related term pages link back through descriptive anchors instead of routing visitors through search.",
  "landing-page": "A campaign landing page can match the promise in its referring message, explain one offer, answer the main objections, and provide a measurable next action without removing essential trust information.",
  "service-page": "A web-design service page should explain who the work fits, what problems it addresses, the process and boundaries, relevant evidence, pricing context, and the next step.",
  "location-page": "A legitimate location page can describe an actual office or service operation, local contact and access details, relevant work, and distinct customer information rather than swapping city names in one template.",
  "version-control": "A content team can compare revisions, review who changed a definition, restore the prior text, and connect the approved revision to the deployed release.",
  build: "A static-site build can validate content, compile components, generate 153 glossary HTML pages, fingerprint shared assets, and fail before deployment if a route collides.",
  "production-environment": "The live site can use production analytics identifiers and public forms, while a separate preview uses test configuration and restricted access so review activity does not contaminate operating data.",
  "staging-environment": "A staging deployment can let reviewers test a new sitemap and redirects against production-like output without making the URLs visible on the public domain.",
  rollback: "If a release breaks navigation, the team can restore the prior known deployment immediately, preserve evidence about the failed version, and correct the issue on a new branch.",
  database: "A contact workflow might store approved submissions in a controlled database with access and retention rules, while a public glossary needs no database at all because its pages are prebuilt.",
  integration: "Connecting a website form to a CRM requires agreement on fields, authentication, validation, duplicate handling, failure alerts, consent, and ownership of the resulting records.",
  "api-endpoint": "A `/api/contact` endpoint can accept a documented POST body, reject invalid or abusive requests, avoid exposing secrets, and return explicit success and error statuses.",
  authentication: "An administrator signs in with a verified identity before reaching the website editor; the system then separately determines which sites and actions that identity may access.",
  authorization: "Two authenticated users can have different authorization: an editor may change draft content while only a release owner may publish to production.",
  credential: "A production deployment credential can be stored in a secret broker, restricted to one Pages project, injected only into the deployment process, and revoked without changing source.",
  "two-factor-authentication": "A registrar account can require a password plus a hardware or authenticator-code factor, with recovery codes stored securely and account recovery ownership documented.",
  workflow: "A glossary release workflow can move from editorial review to static build, automated crawl, private preview, owner approval, Git merge, deployment, and live verification.",
  monitoring: "A scheduled check can request the homepage, sitemap, important forms, and representative assets, alert on status or content changes, and preserve enough evidence for diagnosis.",
  lead: "A message containing a real project need and contact path may be a lead, while an anonymous visit or spam submission should remain outside the lead count.",
  "lead-generation": "A local service site can generate leads by helping the right visitor understand the service, trust the provider, and complete a working call or inquiry path.",
  "qualified-lead": "An inquiry for an offered service, in the service area, with an actionable timeline and valid contact details may meet the business's documented qualification rule.",
  "conversion-rate": "If 20 of 1,000 eligible sessions produce the defined inquiry action, the measured session conversion rate is 2 percent, subject to the tracking and eligibility rules used.",
  metric: "A qualified-inquiry metric should state what counts, the source system, deduplication rule, date window, unit, exclusions, and the business decision it informs.",
  "vanity-metrics": "A dashboard celebrating raw traffic spikes without explaining lead quality, page context, or next actions is often leaning on vanity metrics.",
  "first-party-data": "A business may collect inquiry details directly through its form, document why each field is needed, limit access, retain the record only as long as required, and disclose the practice accurately.",
  cookie: "A session cookie can maintain an authenticated state with secure attributes and a short lifetime, while an analytics cookie may require a different consent and retention decision.",
  "consent-management": "A site can delay optional analytics until the visitor makes a clear choice, remember that choice appropriately, and provide a practical way to change it later.",
  "personal-data": "A contact form's name, email, telephone number, message, and technical request metadata may all require purpose, access, disclosure, retention, and deletion decisions.",
  "data-retention": "A business can retain unsuccessful inquiry records for a defined operational period, delete them on schedule, and preserve only records required for a documented legal or security purpose.",
  backlink: "A local trade association may link to a member's relevant safety guide because it is genuinely useful; that editorial reference is a backlink to the guide.",
  "local-citation": "A chamber directory can list a business's current name, address, phone, category, and website, creating a citation even when the listing link is absent or nofollowed.",
  "nap-consistency": "A business that changes telephone numbers should update its website, Business Profile, major directories, and operational records so customers do not encounter conflicting NAP details.",
  "ai-agent": "An agent can gather approved route evidence, run deterministic validators, and draft a report while requiring a person to approve any production deployment or account change.",
  "large-language-model": "A language model can draft a glossary example from supplied source context, but factual review and release controls still determine whether the text is accurate and publishable.",
  prompt: "A content-review prompt can specify the audience, canonical source, forbidden claims, output fields, and requirement to flag uncertainty instead of inventing missing facts.",
  platform: "A website platform may combine editing, hosting, forms, analytics, and deployment; an ownership review separates which data and capabilities can be exported from each layer.",
  "website-architecture": "A service site can organize one overview, distinct service pages, industry decision pages, a resource library, and a glossary with direct links that reflect how visitors explore.",
  dashboard: "An operating dashboard can place qualified inquiries, source mix, form failures, and measurement caveats together so a traffic increase is not mistaken for business improvement.",
  baseline: "Before a redesign, a team can record current crawl errors, qualified inquiries, page speed, conversion definitions, and date ranges so later comparisons use the same measurement rules.",
  "source-code": "The source code can live in an owner-controlled repository, while the build process produces public HTML, CSS, and JavaScript that can be deployed and reproduced from a commit.",
  codebase: "A codebase may contain the website application, content registries, tests, scripts, and infrastructure definitions that must be reviewed together before changing a shared route contract.",
  cutover: "A domain cutover plan can freeze content, verify the new build, lower DNS risk where appropriate, switch traffic, test apex and `www`, monitor errors, and retain a rollback route.",
  "http-status-code": "A monitoring report can distinguish a `200` canonical page, a `301` historical redirect, a `404` missing route, and a `503` temporary outage instead of judging only visible text.",
  "not-found-404": "A removed mistyped URL should return a real `404` with useful navigation, while a verified historical service URL with a replacement should return a direct `301` instead.",
  "redirect-301": "When `/old-service/` permanently moves to `/services/current-service/`, both slash variants can return `301` directly to the final canonical URL with no intermediate hop.",
  "domain-registration": "The owner can register the domain in a business-controlled account, enable renewal and two-factor authentication, document recovery, and grant a provider limited DNS access separately.",
  cloudflare: "A static site can use Cloudflare Pages for deployment and edge delivery while keeping DNS ownership, source control, analytics, and form systems governed as separate assets.",
  "cloudflare-turnstile": "A public inquiry form can require a validated Turnstile token at the form endpoint, handle unavailable challenges accessibly, and avoid treating the client-side widget alone as proof.",
  "cloudflare-d1": "A small Cloudflare application might store structured records in D1 with migrations and backups, while a static glossary should avoid D1 because no runtime data is required.",
  umami: "A self-hosted Umami installation can record privacy-conscious aggregate page and event data under a defined retention and access policy without receiving form message contents.",
  ssh: "An operations account can use a dedicated SSH key restricted to the Pi, verify the host key, log access, and expose only the commands required by the deployment lane.",
  "artificial-intelligence": "A business may use AI to summarize approved analytics or draft internal options while requiring human validation for factual claims, customer communication, and consequential actions.",
  wcag: "A release review can test applicable WCAG 2.2 Level A and AA criteria across keyboard, focus, contrast, labels, errors, zoom, semantics, and responsive behavior.",
  "assistive-technology": "A screen-reader user can navigate the glossary by landmarks and headings, hear descriptive link labels, open a definition link by keyboard, and return without encountering a focus trap.",
  b2b: "A B2B engineering service page may need to satisfy an operational buyer, technical reviewer, budget owner, and procurement contact before one organization submits an inquiry.",
  faq: "A service FAQ can answer whether a smaller project is possible, what ownership the client retains, what information is needed to quote, and what the next step actually commits to.",
  "ip-address": "A web server may retain an IP address briefly for abuse investigation, restrict the log to operators, and document the field and deletion schedule in its privacy and security records.",
  "user-agent": "A support log might show that an error occurred in a particular browser family, but the user-agent string alone should not authorize access or identify a person.",
  "do-not-track": "If the site's privacy page says first-party analytics honors DNT, an automated browser check can send `DNT: 1` and confirm that the analytics request does not fire.",
  "browser-storage": "A site can use localStorage for a device-only display preference while avoiding sensitive account or inquiry data that would remain readable to scripts on that origin.",
  "page-view": "Opening one page, refreshing it, and revisiting it later may produce several page views even though only one person and no business inquiry are involved.",
  "request-log": "A bounded release log can record route, method, status, and time for failed asset requests, limit operator access, and expire after the troubleshooting window.",
  "form-endpoint": "A contact endpoint can validate field lengths and consent, verify abuse protection, send an approved notification, store the required record, and return a non-ambiguous response.",
  crawlability: "A glossary page linked from the hub, included in the sitemap, returning `200`, and containing server-rendered HTML is crawlable even though indexing remains a separate decision.",
  indexability: "A self-canonical glossary page with `index, follow`, a successful status, substantive visible content, and no conflicting header is technically indexable but not guaranteed to be indexed.",
  "robots-directive": "A release test can inspect both the HTML meta tag and response headers for every page so a template-level `noindex` cannot silently affect an entire section.",
  "redirect-chain": "Instead of `/a` redirecting to `/b` and then `/c`, the migration registry can send `/a` and `/b` directly to canonical `/c`.",
  "orphaned-page": "A detail page generated successfully but absent from the hub and every related-term link would be orphaned even if its URL appeared in the XML sitemap.",
  "website-plugin": "Before replacing a CMS, a team can inventory which plugin handles forms, where its submissions live, whether its data exports, and what will replace its behavior.",
  "title-tag": "The Vanity Metrics page can use “Vanity Metrics Definition | Boho Digital Services,” while its H1 remains “Vanity metrics” and its description summarizes the visible definition.",
  "attribution-model": "One report may credit the final branded search before an inquiry, while another credits the original local-directory visit; both can be internally correct under different models.",
  "website-tracking": "A release checklist can verify that page views fire once, form success fires only after acceptance, excluded personal fields never enter event payloads, and preview traffic stays separate.",
  "data-normalization": "A report can map `phone_call`, `call`, and `tracked-call` source labels into one governed event name while retaining each source system and its original record.",
  "topic-cluster": "A technical SEO cluster can connect canonical URLs, robots directives, crawlability, indexability, redirects, and sitemaps through distinct pages that answer different questions.",
  "open-source-software": "A business can deploy an open-source analytics tool after reviewing its license, dependencies, update process, data behavior, operator access, and recovery plan.",
  "mit-license": "A repository using MIT-licensed code can preserve the required license notice while separately documenting the licenses for photographs, fonts, logos, and other dependencies.",
  "self-hosted": "Running analytics on an organization-controlled server can improve control over configuration and data flow, but the organization must also patch, monitor, back up, and recover it.",
  "least-privilege": "A deployment credential can publish only to the named Pages project, while DNS and account administration require a separate credential that the release process never receives.",
  "search-property": "A domain property can cover protocol and subdomain variations, while a URL-prefix property may be useful for a specific host; the team should know which property holds the historical reports.",
  "call-tracking": "A campaign can use an owner-controlled forwarding number and count calls longer than a documented threshold, while sales review determines which calls were actually qualified.",
  css: "A media query can change a glossary content grid from two columns to one at narrow widths while preserving source order, readable line length, and visible keyboard focus.",
  "magnetic-resonance-imaging": "A research protocol can acquire several MRI sequences with different contrast, document motion and artifacts, and retain acquisition parameters so later interpretation reflects how each image was produced.",
  "functional-magnetic-resonance-imaging": "An fMRI study can compare a modeled task condition with a control condition across repeated measurements, then report preprocessing, statistical thresholds, uncertainty, and limitations alongside activation maps.",
  "ordinary-differential-equation": "A population model can use an ODE to specify how a quantity changes over time, solve trajectories under several parameter values, and compare those trajectories with observed measurements without treating the model as proof.",
});
