export type KnowledgeSource = {
  id: string;
  label: string;
  publisher: string;
  url: string;
};

export type GlossaryCategory =
  | "Web foundations"
  | "Source and delivery"
  | "APIs and automation"
  | "Search and measurement";

export type GlossaryEntry = {
  term: string;
  slug: string;
  aliases?: string[];
  category: GlossaryCategory;
  shortDefinition: string;
  definition: string;
  whyItMatters: string;
  commonMisunderstanding: string;
  relatedTermSlugs?: string[];
  sourceIds: string[];
};

export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "mdn-web",
    label: "How the web works",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works",
  },
  {
    id: "mdn-server",
    label: "What is a web server?",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/What_is_a_web_server",
  },
  {
    id: "mdn-http",
    label: "HTTP",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP",
  },
  {
    id: "rfc-dns",
    label: "RFC 1034: Domain names — concepts and facilities",
    publisher: "RFC Editor / IETF",
    url: "https://www.rfc-editor.org/info/rfc1034/",
  },
  {
    id: "cloudflare-dns",
    label: "DNS concepts",
    publisher: "Cloudflare Developers",
    url: "https://developers.cloudflare.com/dns/concepts/",
  },
  {
    id: "cloudflare-pages-limits",
    label: "Cloudflare Pages limits",
    publisher: "Cloudflare Developers",
    url: "https://developers.cloudflare.com/pages/platform/limits/",
  },
  {
    id: "cloudflare-pages-pricing",
    label: "Cloudflare Pages Functions pricing",
    publisher: "Cloudflare Developers",
    url: "https://developers.cloudflare.com/pages/functions/pricing/",
  },
  {
    id: "github-repositories",
    label: "About repositories",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories",
  },
  {
    id: "github-best-practices",
    label: "Best practices for repositories",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/repositories/creating-and-managing-repositories/best-practices-for-repositories",
  },
  {
    id: "github-pages",
    label: "Using custom workflows with GitHub Pages",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages",
  },
  {
    id: "github-rest",
    label: "GitHub REST API documentation",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/rest",
  },
  {
    id: "github-actions-api",
    label: "REST API endpoints for GitHub Actions",
    publisher: "GitHub Docs",
    url: "https://docs.github.com/en/rest/actions",
  },
  {
    id: "google-api-keys",
    label: "Manage API keys",
    publisher: "Google Cloud Documentation",
    url: "https://cloud.google.com/docs/authentication/api-keys",
  },
  {
    id: "mcp-architecture",
    label: "Model Context Protocol architecture overview",
    publisher: "Model Context Protocol",
    url: "https://modelcontextprotocol.io/docs/learn/architecture",
  },
  {
    id: "python-library",
    label: "The Python Standard Library",
    publisher: "Python Software Foundation",
    url: "https://docs.python.org/3/library/",
  },
  {
    id: "python-urllib",
    label: "urllib — URL handling modules",
    publisher: "Python Software Foundation",
    url: "https://docs.python.org/3/library/urllib.html",
  },
  {
    id: "robots-rfc",
    label: "RFC 9309: Robots Exclusion Protocol",
    publisher: "RFC Editor / IETF",
    url: "https://www.rfc-editor.org/rfc/rfc9309.html",
  },
  {
    id: "google-analytics",
    label: "Google Analytics Data API overview",
    publisher: "Google for Developers",
    url: "https://developers.google.com/analytics/devguides/reporting/data/v1",
  },
  {
    id: "google-search-console",
    label: "Search Console API",
    publisher: "Google for Developers",
    url: "https://developers.google.com/webmaster-tools",
  },
  {
    id: "google-business-profile",
    label: "Google Business Profile APIs",
    publisher: "Google for Developers",
    url: "https://developers.google.com/my-business",
  },
  {
    id: "google-business-policy",
    label: "Business Profile APIs policies",
    publisher: "Google for Developers",
    url: "https://developers.google.com/my-business/content/policies",
  },
];

export const sourcesById = new Map(
  knowledgeSources.map((source) => [source.id, source]),
);

export const glossaryEntries: GlossaryEntry[] = [
  {
    term: "Server",
    slug: "server",
    category: "Web foundations",
    shortDefinition: "A computer or program that receives requests and provides files, data, or actions to another computer called a client.",
    definition: "A server is the part of a computer system that responds to requests. The word can describe physical hardware, software running on that hardware, or a managed cloud service that hides the hardware from its user. A web browser is a client; it asks a web server for a page, image, file, or response.",
    whyItMatters: "When a provider says something is “on the server,” the owner should ask which account controls it, what is stored there, who can access it, how it is backed up, and how it can be moved.",
    commonMisunderstanding: "A server is not automatically a single box in one room. Modern services often distribute work across many machines and locations.",
    relatedTermSlugs: ["web-server", "hosting", "client", "http"],
    sourceIds: ["mdn-server", "mdn-web"],
  },
  {
    term: "Web server",
    slug: "web-server",
    category: "Web foundations",
    shortDefinition: "Hardware and software that accept web requests and return pages, files, or application responses through HTTP.",
    definition: "A web server accepts HTTP requests from browsers and other clients. It may return a stored HTML file, route a request to application code, or generate a response from data. Static hosting can serve prepared files; dynamic applications may execute code for each request.",
    whyItMatters: "The server model affects maintenance, cost, performance, security responsibilities, and portability.",
    commonMisunderstanding: "The web server is not the domain name. DNS helps a browser find the service; the server responds after the request arrives.",
    relatedTermSlugs: ["server", "http", "static-site", "dns"],
    sourceIds: ["mdn-server", "mdn-http"],
  },
  {
    term: "Client",
    slug: "client",
    category: "Web foundations",
    shortDefinition: "A device or program—such as a browser—that requests information or actions from a server.",
    definition: "In client-server systems, the client initiates a request. A browser requesting a webpage is a client. A Python script requesting an API is also a client. The same machine can act as a client in one exchange and a server in another.",
    whyItMatters: "Knowing which side initiates a request helps clarify where credentials, validation, caching, and errors belong.",
    commonMisunderstanding: "“Client” can mean the customer in business language or the requesting program in technical language; context matters.",
    relatedTermSlugs: ["server", "browser", "api"],
    sourceIds: ["mdn-web"],
  },
  {
    term: "Browser",
    slug: "browser",
    category: "Web foundations",
    shortDefinition: "Software that requests web resources, interprets them, and presents an interactive page to a visitor.",
    definition: "A browser such as Firefox, Chrome, Safari, or Edge requests resources from web servers and interprets HTML, CSS, JavaScript, images, and related files. Browsers differ, screen sizes differ, and assistive technologies interact with the same structure in different ways.",
    whyItMatters: "A website must be tested as a flexible system, not approved from one desktop screenshot.",
    commonMisunderstanding: "A browser is not a search engine. A browser displays the web; a search engine helps people find pages.",
    relatedTermSlugs: ["client", "http", "responsive-design"],
    sourceIds: ["mdn-web"],
  },
  {
    term: "Domain name",
    slug: "domain-name",
    aliases: ["domain"],
    category: "Web foundations",
    shortDefinition: "A human-readable name used to reach internet services, controlled through registration and DNS rather than by the website files themselves.",
    definition: "A domain name is a named location in the Domain Name System. Registration establishes control of the name for a period; DNS records then direct website, email, verification, and other traffic. The domain, hosting account, website source, and business email are separate assets even when one vendor sells all of them.",
    whyItMatters: "The business should know who owns the registration, controls renewal and recovery, and can change the DNS records.",
    commonMisunderstanding: "Buying hosting does not necessarily give the buyer independent ownership of the domain, and moving a website does not always require transferring the domain registration.",
    relatedTermSlugs: ["dns", "nameserver", "hosting"],
    sourceIds: ["rfc-dns", "cloudflare-dns"],
  },
  {
    term: "DNS",
    slug: "dns",
    aliases: ["Domain Name System"],
    category: "Web foundations",
    shortDefinition: "The distributed naming system that directs a domain to website, email, verification, and other internet services.",
    definition: "DNS translates human-readable names into records that software can use. An address record can direct a hostname toward a web service; MX records direct email; TXT records often verify ownership or publish policy. Authoritative nameservers provide the final records for a domain's zone.",
    whyItMatters: "Changing DNS without inventorying every record can break the website, email, verification, or another service that appears unrelated.",
    commonMisunderstanding: "DNS is not hosting. It tells clients where to go; it does not contain the full website application.",
    relatedTermSlugs: ["domain-name", "nameserver", "dns-record", "hosting"],
    sourceIds: ["rfc-dns", "cloudflare-dns"],
  },
  {
    term: "Nameserver",
    slug: "nameserver",
    category: "Web foundations",
    shortDefinition: "A DNS server that answers questions about names; authoritative nameservers provide the final records for a domain's zone.",
    definition: "Nameservers participate in DNS resolution. For a business owner, the most important set is usually the authoritative nameservers named at the registrar. Those servers hold the DNS records that direct the domain's website, email, and verification traffic.",
    whyItMatters: "Changing nameservers effectively changes which DNS record set is authoritative, so a missing copied record can interrupt services.",
    commonMisunderstanding: "A nameserver change is not merely a website setting; it can affect every DNS-dependent service for the domain.",
    relatedTermSlugs: ["dns", "dns-record", "domain-name"],
    sourceIds: ["cloudflare-dns", "rfc-dns"],
  },
  {
    term: "DNS record",
    slug: "dns-record",
    category: "Web foundations",
    shortDefinition: "A typed instruction in DNS that directs traffic or publishes information for a domain or hostname.",
    definition: "DNS records are typed entries in an authoritative zone. Common examples include A or AAAA address records, CNAME aliases, MX email routing records, and TXT records used for verification or policy. The exact set should be inventoried before a migration.",
    whyItMatters: "A clean website launch can still break business email if the DNS record inventory is incomplete.",
    commonMisunderstanding: "Not every DNS record belongs to the website. Some support mail, security, ownership verification, or third-party services.",
    relatedTermSlugs: ["dns", "nameserver", "domain-name"],
    sourceIds: ["cloudflare-dns"],
  },
  {
    term: "Hosting",
    slug: "hosting",
    category: "Web foundations",
    shortDefinition: "The service and infrastructure that make website files or application responses available to internet visitors.",
    definition: "Hosting makes a website reachable. Traditional hosting may provide a server account; static hosting distributes prepared files; application platforms execute code and connect data services. The price can be zero within a platform's current free limits, but domain registration, email, forms, maintenance, and professional work remain separate.",
    whyItMatters: "The right hosting model depends on the site's functionality, traffic, ownership needs, support requirements, and tolerance for platform limits.",
    commonMisunderstanding: "No separate hosting line item does not mean the website costs nothing to build, maintain, support, or operate.",
    relatedTermSlugs: ["server", "static-site", "deployment", "domain-name"],
    sourceIds: ["mdn-server", "cloudflare-pages-limits", "cloudflare-pages-pricing"],
  },
  {
    term: "Static site",
    slug: "static-site",
    category: "Web foundations",
    shortDefinition: "A website whose deployable pages and assets are prepared ahead of requests instead of requiring server code for every visit.",
    definition: "A static site serves prepared HTML, CSS, JavaScript, images, and other assets. It can still be visually rich and interactive. Static describes the delivery model, not a boring design. Forms, search, account data, or other dynamic features can be connected through separate services or functions.",
    whyItMatters: "Static delivery can reduce moving parts and platform cost for brochure, documentation, and many lead-generation sites.",
    commonMisunderstanding: "Static does not mean uneditable or non-responsive; source content can be rebuilt and redeployed whenever approved changes are made.",
    relatedTermSlugs: ["hosting", "deployment", "api"],
    sourceIds: ["mdn-server", "cloudflare-pages-limits"],
  },
  {
    term: "CDN",
    slug: "cdn",
    aliases: ["content delivery network"],
    category: "Web foundations",
    shortDefinition: "A distributed network that serves cached website resources from locations closer to visitors.",
    definition: "A content delivery network distributes or caches files across multiple locations. A nearby location can answer a request without sending every visitor to one origin server. CDN behavior also affects cache invalidation, headers, security controls, and troubleshooting.",
    whyItMatters: "CDNs can improve delivery speed and resilience, but an outdated cache can make a correct deployment appear unchanged until it is refreshed or expires.",
    commonMisunderstanding: "A CDN does not repair slow source code or poor images automatically; it improves delivery of what it receives.",
    relatedTermSlugs: ["hosting", "server", "deployment"],
    sourceIds: ["mdn-web", "cloudflare-pages-limits"],
  },
  {
    term: "HTTP",
    slug: "http",
    category: "Web foundations",
    shortDefinition: "The request-and-response protocol browsers, servers, and many APIs use to exchange web resources and actions.",
    definition: "HTTP defines how a client requests a resource or action and how a server responds. Responses include status codes such as 200 for success, 301 for a permanent redirect, 404 for not found, and 500-class codes for server failures. HTTPS is HTTP protected in transit with TLS.",
    whyItMatters: "Status codes, methods, headers, caching, and redirects affect visitors, integrations, and search systems.",
    commonMisunderstanding: "A page that visually displays an error can still return a 200 status, confusing crawlers and monitoring; the protocol response matters.",
    relatedTermSlugs: ["server", "client", "api", "tls"],
    sourceIds: ["mdn-http", "mdn-web"],
  },
  {
    term: "TLS",
    slug: "tls",
    aliases: ["SSL", "HTTPS certificate"],
    category: "Web foundations",
    shortDefinition: "The security protocol used by HTTPS to protect data while it travels between a client and server.",
    definition: "Transport Layer Security helps a browser verify the service it reached and encrypts information while it travels across the network. Certificates connect domain names to cryptographic identities. Modern providers often automate certificate issuance and renewal.",
    whyItMatters: "HTTPS is a baseline for safe transport, forms, browser trust, and modern web behavior.",
    commonMisunderstanding: "The browser lock does not prove that the business, page claims, stored data, or application code are trustworthy; it protects the connection in transit.",
    relatedTermSlugs: ["http", "domain-name", "hosting"],
    sourceIds: ["mdn-http"],
  },
  {
    term: "URL",
    slug: "url",
    category: "Web foundations",
    shortDefinition: "An address that identifies a resource by scheme, host, path, and optional query or fragment information.",
    definition: "A URL identifies where and how to request a resource. In `https://example.com/services/?source=map#pricing`, HTTPS is the scheme, example.com is the host, `/services/` is the path, `source=map` is a query, and `pricing` is a fragment.",
    whyItMatters: "URL changes affect bookmarks, links, analytics, redirects, and search history. A redesign needs a URL inventory before launch.",
    commonMisunderstanding: "A domain is only one part of a URL; changing page paths can cause loss even when the domain stays the same.",
    relatedTermSlugs: ["domain-name", "http", "redirect"],
    sourceIds: ["mdn-web"],
  },
  {
    term: "Redirect",
    slug: "redirect",
    category: "Web foundations",
    shortDefinition: "A response that tells a browser or crawler to request a resource at a different URL.",
    definition: "A redirect preserves a path from an old URL to an appropriate new URL. Permanent and temporary redirects communicate different intent. A migration plan should map each valuable old route to the closest relevant destination rather than sending every page to the homepage.",
    whyItMatters: "Good redirects reduce broken links, preserve useful visitor paths, and help search systems understand a move.",
    commonMisunderstanding: "A redirect is not a substitute for moving content thoughtfully; irrelevant mass redirects can hide rather than solve a migration problem.",
    relatedTermSlugs: ["url", "http", "deployment"],
    sourceIds: ["mdn-web", "cloudflare-pages-limits"],
  },
  {
    term: "Responsive design",
    slug: "responsive-design",
    category: "Web foundations",
    shortDefinition: "A layout approach that adapts content and interaction to different screen sizes, zoom levels, input methods, and available space.",
    definition: "Responsive design uses flexible dimensions, layout rules, type scaling, and content priorities so a site remains readable and usable across phones, tablets, laptops, large screens, and zoomed views. It is a behavior, not a separate mobile website.",
    whyItMatters: "A site can look polished at one width and still fail when text wraps, cards reorder, navigation changes, or a user zooms.",
    commonMisunderstanding: "Passing a single mobile screenshot is not comprehensive responsive or accessibility testing.",
    relatedTermSlugs: ["browser", "static-site"],
    sourceIds: ["mdn-web"],
  },
  {
    term: "Git",
    slug: "git",
    category: "Source and delivery",
    shortDefinition: "A version-control system that records changes to files so work can be compared, reviewed, branched, and restored.",
    definition: "Git stores a history of project changes. Developers work in repositories, record commits, create branches, and merge reviewed work. Git can be used locally or synchronized with a hosting/collaboration service such as GitHub.",
    whyItMatters: "A readable history and recoverable versions reduce dependence on one person's machine and make handoff safer.",
    commonMisunderstanding: "Git and GitHub are related but not identical: Git is the version-control system; GitHub is a service that hosts and manages Git repositories and workflows.",
    relatedTermSlugs: ["repository", "branch", "commit"],
    sourceIds: ["github-repositories"],
  },
  {
    term: "GitHub",
    slug: "github",
    category: "Source and delivery",
    shortDefinition: "A hosted platform for Git repositories, code review, permissions, documentation, automation, releases, and related project operations.",
    definition: "GitHub stores repositories containing code, files, and revision history. It also provides issues, pull requests, automation through Actions, release records, APIs, access controls, and static publishing through GitHub Pages. Repositories can be public or private depending on the required ownership and disclosure model.",
    whyItMatters: "GitHub can provide a portable, reviewable system of record for public-facing website source and documentation without placing secrets in the repository.",
    commonMisunderstanding: "Public-facing website content does not require credentials to be stored publicly. Source visibility, deployed visibility, and secret storage are separate decisions.",
    relatedTermSlugs: ["git", "repository", "deployment", "ci-cd"],
    sourceIds: ["github-repositories", "github-best-practices"],
  },
  {
    term: "Repository",
    slug: "repository",
    aliases: ["repo"],
    category: "Source and delivery",
    shortDefinition: "A project container holding files, revision history, branches, and collaboration records.",
    definition: "A repository contains a project's source files and history. On GitHub it may also include issues, pull requests, Actions workflows, releases, access roles, and project documentation. A clone is a full working copy that can be kept outside GitHub.",
    whyItMatters: "Repository ownership and recovery are central to portability. A client should know which account or organization owns the source of a production website.",
    commonMisunderstanding: "The repository is not necessarily the live server. A deployment process builds or copies approved source into the hosting environment.",
    relatedTermSlugs: ["git", "branch", "commit", "deployment"],
    sourceIds: ["github-repositories"],
  },
  {
    term: "Branch",
    slug: "branch",
    category: "Source and delivery",
    shortDefinition: "A parallel line of repository work used to develop or review changes without immediately altering the main version.",
    definition: "A Git branch lets a change develop separately from the primary line. A branch can be reviewed, tested, previewed, merged, or discarded. Protected branches and review rules can reduce accidental production changes.",
    whyItMatters: "Branches support private review and controlled releases instead of editing the live site directly.",
    commonMisunderstanding: "A branch is not automatically a backup or a live preview; those behaviors depend on the repository and deployment configuration.",
    relatedTermSlugs: ["repository", "commit", "deployment"],
    sourceIds: ["github-repositories", "github-best-practices"],
  },
  {
    term: "Commit",
    slug: "commit",
    category: "Source and delivery",
    shortDefinition: "A recorded repository revision that identifies a specific set of changes and its place in project history.",
    definition: "A commit captures an intentional group of file changes with an identifier, author record, time, parent history, and message. It allows a team to compare versions, locate when behavior changed, and reproduce the exact source used for a release.",
    whyItMatters: "A deployment tied to a commit can be audited and rolled back more reliably than an undocumented file upload.",
    commonMisunderstanding: "A commit records source history; it does not automatically publish or deploy the change.",
    relatedTermSlugs: ["repository", "branch", "deployment"],
    sourceIds: ["github-repositories"],
  },
  {
    term: "Deployment",
    slug: "deployment",
    aliases: ["deploy", "release"],
    category: "Source and delivery",
    shortDefinition: "The controlled process that makes a selected version of source available in a hosting environment.",
    definition: "A deployment may build source files, run checks, upload an artifact, configure runtime values, and switch traffic to the new version. Preview and production deployments serve different risk levels. A rollback restores a previously known version when a release fails.",
    whyItMatters: "A repeatable deployment connects the version reviewed by humans to the version visitors receive.",
    commonMisunderstanding: "Pushing code to a repository does not always deploy it; the trigger and environment rules must be documented.",
    relatedTermSlugs: ["commit", "hosting", "ci-cd"],
    sourceIds: ["github-pages", "cloudflare-pages-limits"],
  },
  {
    term: "CI/CD",
    slug: "ci-cd",
    aliases: ["continuous integration", "continuous delivery"],
    category: "Source and delivery",
    shortDefinition: "Automated checks and release workflows that turn reviewed source changes into tested, deployable versions.",
    definition: "Continuous integration runs repeatable checks when source changes. Continuous delivery or deployment packages and releases approved versions according to defined rules. GitHub Actions is one service that can run these workflows.",
    whyItMatters: "Automation can catch broken builds, missing links, or test failures before visitors see them and can produce a consistent release record.",
    commonMisunderstanding: "Automation is not judgment. A fast automated deployment still needs appropriate review, permissions, secrets handling, and rollback.",
    relatedTermSlugs: ["deployment", "repository", "automation"],
    sourceIds: ["github-pages", "github-actions-api"],
  },
  {
    term: "API",
    slug: "api",
    aliases: ["application programming interface"],
    category: "APIs and automation",
    shortDefinition: "A defined way for one program to request data or actions from another program.",
    definition: "An application programming interface defines available operations, inputs, outputs, authentication, permissions, limits, and error behavior. Web APIs commonly use HTTP and structured formats such as JSON. An API can support reporting, publishing, account management, or other automation when the owner and provider permit it.",
    whyItMatters: "An API can replace repetitive manual work, but it also creates data, access, quota, maintenance, and failure responsibilities.",
    commonMisunderstanding: "Having API access does not mean every action is authorized or safe to automate. Provider policy and user approval still apply.",
    relatedTermSlugs: ["api-key", "oauth", "json", "webhook"],
    sourceIds: ["mdn-http", "github-rest"],
  },
  {
    term: "API key",
    slug: "api-key",
    category: "APIs and automation",
    shortDefinition: "A credential-like string used by an API to associate a request with a project, quota, or permitted capability.",
    definition: "An API key is supplied with an API request so the provider can identify a project, apply quotas, or permit configured access. Different vendors give keys different security meaning. Keys should be restricted where supported, stored outside public source, rotated when exposed, and granted no more capability than required.",
    whyItMatters: "A leaked key can consume quota, expose data, or enable actions depending on the service. The key's actual permissions must be documented rather than assumed.",
    commonMisunderstanding: "An API key is not universally the same as a user identity or full authorization. Some keys identify only a project; stronger actions may require OAuth or another credential.",
    relatedTermSlugs: ["api", "oauth", "environment-variable"],
    sourceIds: ["google-api-keys"],
  },
  {
    term: "OAuth",
    slug: "oauth",
    category: "APIs and automation",
    shortDefinition: "A delegated authorization framework that lets a user grant limited application access without giving the application the user's password.",
    definition: "OAuth supports delegated access through scopes and tokens. A user or administrator approves defined permissions, and the application receives a token rather than the account password. Tokens may expire or be revoked, and the application must protect them like other secrets.",
    whyItMatters: "OAuth is often the appropriate model for accessing a client's Google or other vendor account while preserving client ownership and revocation control.",
    commonMisunderstanding: "OAuth approval is not unlimited permission. Scopes, account roles, provider policy, and the specific user action still constrain what the integration should do.",
    relatedTermSlugs: ["api", "api-key", "environment-variable"],
    sourceIds: ["google-analytics", "google-business-profile"],
  },
  {
    term: "Environment variable",
    slug: "environment-variable",
    category: "APIs and automation",
    shortDefinition: "Runtime configuration supplied outside application source, commonly used for environment-specific values and secret references.",
    definition: "An environment variable supplies configuration to a process when it runs. It can distinguish preview from production settings or provide access to a secret managed by the hosting platform. It prevents hard-coding a credential into public source, but it still requires access controls and rotation procedures.",
    whyItMatters: "Public website source can remain portable and reviewable while credentials stay in restricted platform configuration.",
    commonMisunderstanding: "Moving a secret into an environment variable does not make every user or log safe; the runtime, deployment, debugging, and access paths still need review.",
    relatedTermSlugs: ["api-key", "deployment"],
    sourceIds: ["github-actions-api", "google-api-keys"],
  },
  {
    term: "Webhook",
    slug: "webhook",
    category: "APIs and automation",
    shortDefinition: "An event-driven HTTP message one system sends to another when something changes.",
    definition: "A webhook lets a provider notify another system instead of making the receiver check repeatedly. A repository can notify a build service after a push; a form service can notify an approved workflow after a submission. Receivers should verify authenticity, handle retries, and avoid logging sensitive payloads unnecessarily.",
    whyItMatters: "Webhooks can make automation timely and efficient, but they create an inbound endpoint that needs validation and monitoring.",
    commonMisunderstanding: "A webhook does not guarantee exactly-once delivery. Workflows must handle duplicate, delayed, or failed messages.",
    relatedTermSlugs: ["api", "automation", "http"],
    sourceIds: ["github-rest", "mdn-http"],
  },
  {
    term: "JSON",
    slug: "json",
    category: "APIs and automation",
    shortDefinition: "A structured text format commonly used to exchange named values, lists, and objects between software systems.",
    definition: "JavaScript Object Notation represents structured data with objects, arrays, strings, numbers, booleans, and null values. Many APIs and MCP messages use JSON because it is readable by many programming languages and straightforward to validate against a schema.",
    whyItMatters: "Structured responses can be stored, compared, transformed, or turned into reports more reliably than copying values manually from a dashboard.",
    commonMisunderstanding: "JSON describes structure, not truth. A valid JSON response can still contain stale, incomplete, or misunderstood data.",
    relatedTermSlugs: ["api", "mcp"],
    sourceIds: ["mcp-architecture", "github-rest"],
  },
  {
    term: "Automation",
    slug: "automation",
    category: "APIs and automation",
    shortDefinition: "A repeatable process performed by software according to defined triggers, inputs, rules, permissions, and review points.",
    definition: "Automation can collect approved data, validate files, generate reports, compare changes, schedule checks, or deploy reviewed source. Good automation records what happened, handles errors, limits permissions, and reserves judgment-heavy or consequential actions for human review.",
    whyItMatters: "It can reduce repetitive labor and make checks consistent, but only when ownership and failure behavior are clear.",
    commonMisunderstanding: "Automating a weak or unauthorized process makes the weakness faster; it does not make the decision correct.",
    relatedTermSlugs: ["api", "ci-cd", "webhook"],
    sourceIds: ["python-library", "github-actions-api"],
  },
  {
    term: "Model Context Protocol",
    slug: "mcp",
    aliases: ["MCP"],
    category: "APIs and automation",
    shortDefinition: "A client-server protocol that lets AI applications discover approved tools, resources, and prompt templates through defined connections.",
    definition: "Model Context Protocol defines how an MCP host and client communicate with one or more MCP servers. Servers can expose tools for actions, resources for context, and prompts for reusable interaction templates. The protocol also defines lifecycle and transport behavior; SDKs implement those rules for specific languages.",
    whyItMatters: "MCP can make approved business systems available through one consistent interface while preserving a visible boundary around each server's capabilities.",
    commonMisunderstanding: "Connecting an MCP server does not grant unlimited authority. The server exposes only defined capabilities, and the host, user, authentication, permissions, and application policy still govern use.",
    relatedTermSlugs: ["mcp-server", "mcp-client", "mcp-tool", "mcp-resource"],
    sourceIds: ["mcp-architecture"],
  },
  {
    term: "MCP server",
    slug: "mcp-server",
    category: "APIs and automation",
    shortDefinition: "A program that exposes a defined set of MCP tools, resources, or prompts to an approved MCP client.",
    definition: "An MCP server advertises capabilities through the protocol. It may run locally as a process or remotely over HTTP. A server can wrap file access, databases, APIs, search systems, or business operations, but it should expose only what its purpose and permissions require.",
    whyItMatters: "A narrow server boundary can make powerful automation understandable, testable, and replaceable.",
    commonMisunderstanding: "The word server does not imply a public machine. A local MCP server can run on the same computer as the client, while a remote server can run elsewhere.",
    relatedTermSlugs: ["mcp", "mcp-client", "mcp-tool", "server"],
    sourceIds: ["mcp-architecture"],
  },
  {
    term: "MCP client",
    slug: "mcp-client",
    category: "APIs and automation",
    shortDefinition: "The protocol component inside an AI host that maintains a connection to one MCP server.",
    definition: "An MCP host can create a client connection for each server. The client negotiates capabilities, lists available features, sends approved calls, and receives results through the selected transport. The host presents those capabilities to the user or model according to product policy.",
    whyItMatters: "Separating host, client, and server clarifies which layer manages user experience, protocol communication, and business capability.",
    commonMisunderstanding: "The client is not the same thing as the language model and not the same thing as the server it connects to.",
    relatedTermSlugs: ["mcp", "mcp-server", "client"],
    sourceIds: ["mcp-architecture"],
  },
  {
    term: "MCP tool",
    slug: "mcp-tool",
    category: "APIs and automation",
    shortDefinition: "An executable function an MCP server advertises for the client to request with defined inputs and outputs.",
    definition: "An MCP tool represents an action such as requesting an API report, searching an approved index, validating a file, or creating a controlled record. The tool definition describes its name, purpose, and input schema; the server implements the action and returns structured content.",
    whyItMatters: "Explicit tool contracts make actions more inspectable than vague “AI can access everything” claims.",
    commonMisunderstanding: "A listed tool is a capability, not blanket authorization to call it in every context. Consequential calls may still require human approval.",
    relatedTermSlugs: ["mcp", "mcp-server", "api"],
    sourceIds: ["mcp-architecture"],
  },
  {
    term: "MCP resource",
    slug: "mcp-resource",
    category: "APIs and automation",
    shortDefinition: "Contextual data an MCP server makes readable through an addressable resource interface.",
    definition: "An MCP resource can expose file contents, database records, API responses, or other context without presenting the access as an action tool. Resources can be listed or retrieved according to the server's implementation and permissions.",
    whyItMatters: "Resources help separate reading approved context from taking an action, which supports clearer permission design.",
    commonMisunderstanding: "A resource is not automatically public or persistent; access depends on the connection, server, credentials, and source system.",
    relatedTermSlugs: ["mcp", "mcp-server", "mcp-tool"],
    sourceIds: ["mcp-architecture"],
  },
  {
    term: "Web crawling",
    slug: "web-crawling",
    category: "Search and measurement",
    shortDefinition: "Automated retrieval and traversal of web resources to inspect, index, monitor, or analyze publicly reachable content.",
    definition: "A crawler requests URLs, reads responses, follows permitted links, and records selected information. Search engines crawl to discover content; technical tools crawl to find broken links, redirects, metadata, index directives, or patterns across a defined sample.",
    whyItMatters: "A crawl can reveal observable structure at scale, but the findings still require interpretation, scope, dates, respectful request rates, and compliance with applicable rules and policies.",
    commonMisunderstanding: "Crawling is not authorization to bypass authentication, access controls, provider terms, privacy expectations, or technical safeguards. `robots.txt` is a crawl preference standard, not an access-control system.",
    relatedTermSlugs: ["crawler", "robots-txt", "xml-sitemap", "http"],
    sourceIds: ["robots-rfc", "python-urllib"],
  },
  {
    term: "Crawler",
    slug: "crawler",
    aliases: ["spider", "bot"],
    category: "Search and measurement",
    shortDefinition: "An automated client that requests web resources and may follow links according to a defined purpose and policy.",
    definition: "A crawler is software acting as a web client. It may discover pages for a search index, audit a website, monitor changes, or collect an approved research sample. Responsible crawlers identify their purpose where appropriate, respect request limits, handle errors, and avoid restricted or unnecessary data.",
    whyItMatters: "Crawler behavior affects server load, data quality, research ethics, and what a crawl can legitimately conclude.",
    commonMisunderstanding: "All bots are not identical. Search crawlers, monitoring agents, accessibility tools, malicious scanners, and private audit crawlers have different purposes and behavior.",
    relatedTermSlugs: ["web-crawling", "robots-txt", "client"],
    sourceIds: ["robots-rfc", "mdn-web"],
  },
  {
    term: "robots.txt",
    slug: "robots-txt",
    category: "Search and measurement",
    shortDefinition: "A top-level text file that publishes crawl rules for automated clients following the Robots Exclusion Protocol.",
    definition: "The Robots Exclusion Protocol defines how a service publishes groups and allow/disallow rules in `/robots.txt`. Cooperative crawlers can use those rules when deciding which paths to request. The file is public and should not list secret paths that would otherwise be unknown.",
    whyItMatters: "It helps coordinate crawl behavior and prevent waste, but it must match the site's intended indexing and technical structure.",
    commonMisunderstanding: "`robots.txt` is not authentication and does not prevent a person or non-compliant program from requesting a public URL.",
    relatedTermSlugs: ["crawler", "web-crawling", "xml-sitemap"],
    sourceIds: ["robots-rfc"],
  },
  {
    term: "XML sitemap",
    slug: "xml-sitemap",
    aliases: ["sitemap"],
    category: "Search and measurement",
    shortDefinition: "A machine-readable list of canonical URLs a site wants eligible crawlers to discover.",
    definition: "An XML sitemap lists selected URLs and optional metadata for discovery. It can help search systems find important pages, especially on a new, large, or poorly linked site. It does not replace internal navigation, guarantee indexing, or establish that every listed page is high quality.",
    whyItMatters: "A launch should include only canonical, public, indexable pages and exclude private, test, thin, and duplicate routes.",
    commonMisunderstanding: "Submitting a sitemap is not a ranking command. Search systems still decide whether and how to crawl and index each URL.",
    relatedTermSlugs: ["robots-txt", "indexing", "url"],
    sourceIds: ["google-search-console", "robots-rfc"],
  },
  {
    term: "Indexing",
    slug: "indexing",
    category: "Search and measurement",
    shortDefinition: "A search system's process of evaluating and storing information about a page for possible retrieval in results.",
    definition: "After discovery and crawling, a search system may process a page and add information about it to an index. Indexing can be affected by accessibility, canonicalization, duplicate content, page quality, directives, status codes, and search-system decisions.",
    whyItMatters: "A published page cannot earn ordinary search visibility if the search system cannot or will not index the preferred version.",
    commonMisunderstanding: "Indexing is not ranking. A page can be indexed without appearing prominently for a particular query.",
    relatedTermSlugs: ["crawler", "robots-txt", "xml-sitemap"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "Google Analytics",
    slug: "google-analytics",
    aliases: ["GA", "GA4"],
    category: "Search and measurement",
    shortDefinition: "Google's event-based analytics product for measuring configured website or application activity and reporting it through an interface and APIs.",
    definition: "Google Analytics records configured events and parameters in a property. The Data API can retrieve report data for dashboards and recurring analysis. The numbers depend on implementation, consent, reporting identity, filters, event design, and data-quality limitations.",
    whyItMatters: "Analytics can connect page and campaign activity to defined actions, but collection should be limited to approved business questions and reconciled with privacy requirements.",
    commonMisunderstanding: "Analytics does not automatically know whether an inquiry became a qualified customer, and a dashboard number is not automatically complete or causal.",
    relatedTermSlugs: ["event", "conversion", "api", "oauth"],
    sourceIds: ["google-analytics"],
  },
  {
    term: "Event",
    slug: "event",
    category: "Search and measurement",
    shortDefinition: "A defined action or occurrence recorded by an analytics system with approved contextual properties.",
    definition: "An analytics event may represent a page view, form start, form submission, phone click, booking click, or another defined interaction. The event name, trigger, parameters, consent behavior, and business question should be documented before collection.",
    whyItMatters: "A disciplined event plan produces a smaller set of interpretable signals instead of a large collection of unused behavioral data.",
    commonMisunderstanding: "Not every click is a conversion or lead. Events record behavior; the business must define which outcomes matter.",
    relatedTermSlugs: ["google-analytics", "conversion", "api"],
    sourceIds: ["google-analytics"],
  },
  {
    term: "Conversion",
    slug: "conversion",
    category: "Search and measurement",
    shortDefinition: "A visitor action the business has deliberately defined as meaningful progress toward an outcome.",
    definition: "A conversion can be a qualified form submission, completed booking, purchase, phone call, directions request, or another valuable action. Primary conversions represent real business outcomes more closely; secondary events can indicate engagement without becoming leads.",
    whyItMatters: "Conversion definitions determine what gets optimized and reported. A bad definition can reward activity that produces no business value.",
    commonMisunderstanding: "A button click is not necessarily a completed outcome, and more conversions are not automatically better if lead quality falls.",
    relatedTermSlugs: ["event", "google-analytics"],
    sourceIds: ["google-analytics"],
  },
  {
    term: "Google Search Console",
    slug: "google-search-console",
    aliases: ["GSC", "Search Console"],
    category: "Search and measurement",
    shortDefinition: "Google's owner-facing service for monitoring and debugging how a verified website appears and performs in Google Search.",
    definition: "Search Console provides search-performance data and technical reports for verified properties. Its API can query search analytics, list verified sites, and manage sitemaps. Data reflects Google Search and has dimensions, date ranges, quotas, and interpretation limits.",
    whyItMatters: "It provides first-party evidence about queries, pages, indexing, and technical issues without pretending to measure every search system or every business outcome.",
    commonMisunderstanding: "Search Console is not Google Analytics. It focuses on Google Search visibility and technical information before and around the visit, not a complete record of on-site behavior.",
    relatedTermSlugs: ["indexing", "xml-sitemap", "api", "oauth"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "Google Business Profile",
    slug: "google-business-profile",
    aliases: ["GBP", "business profile"],
    category: "Search and measurement",
    shortDefinition: "A Google-managed business listing that can appear across Google Search and Maps with approved business information and interactions.",
    definition: "Google Business Profile represents a business location or service context in Google Search and Maps. Eligible owners and authorized managers can maintain location details and supported content. The Business Profile APIs support approved account, location, review, post, media, notification, and performance workflows subject to access and policy.",
    whyItMatters: "For local businesses, accurate ownership, categories, hours, service information, photos, reviews, and website links are part of the customer's discovery and trust path.",
    commonMisunderstanding: "GBP is not a substitute for an owned website, and API access is not permission to automate changes, replies, or lead research without authorization and policy compliance.",
    relatedTermSlugs: ["api", "oauth", "google-search-console"],
    sourceIds: ["google-business-profile", "google-business-policy"],
  },
  {
    term: "SEO",
    slug: "seo",
    aliases: ["search engine optimization"],
    category: "Search and measurement",
    shortDefinition: "Work that improves how search systems can access, understand, and present useful website information without guaranteeing placement.",
    definition: "Search engine optimization coordinates site structure, crawl access, content, internal links, metadata, local information, technical health, and other signals so relevant pages can be discovered and understood. Search systems make their own ranking and presentation decisions.",
    whyItMatters: "SEO should connect pages and technical work to real services, customer questions, and valuable actions rather than chasing isolated ranking numbers.",
    commonMisunderstanding: "No provider controls organic results. SEO can improve eligibility, relevance, clarity, and evidence, but cannot guarantee a position, traffic, leads, or AI citations.",
    relatedTermSlugs: ["technical-seo", "local-seo", "search-intent", "indexing", "metadata"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "Local SEO",
    slug: "local-seo",
    category: "Search and measurement",
    shortDefinition: "SEO focused on helping an eligible business become easier to find, understand, and evaluate in a real local market.",
    definition: "Local SEO coordinates accurate business information, an owned website, eligible business profiles, services, locations or service areas, reviews, local relevance, trust, links, and measurement. The useful approach depends on how the business actually serves customers.",
    whyItMatters: "Local customers often move between maps, profiles, reviews, service pages, calls, directions, and visits before acting.",
    commonMisunderstanding: "Local SEO is not publishing thin pages for every nearby city or repeatedly editing a business profile to appear active.",
    relatedTermSlugs: ["seo", "google-business-profile", "conversion"],
    sourceIds: ["google-business-profile", "google-search-console"],
  },
  {
    term: "Technical SEO",
    slug: "technical-seo",
    category: "Search and measurement",
    shortDefinition: "The technical work that helps the right website pages remain accessible, crawlable, indexable, canonical, fast, and correctly connected.",
    definition: "Technical SEO examines status codes, crawl access, rendering, canonicals, redirects, sitemaps, metadata, internal links, structured data, performance, duplicate routes, and migration behavior. Findings should be prioritized by real impact and risk.",
    whyItMatters: "Strong content can still underperform when search systems or visitors cannot reliably reach, interpret, or use the preferred page.",
    commonMisunderstanding: "A tool's warning count is not a strategy. Many warnings are contextual, duplicated, low impact, or unrelated to the business's immediate problem.",
    relatedTermSlugs: ["seo", "indexing", "redirect", "canonical-url", "xml-sitemap"],
    sourceIds: ["google-search-console", "robots-rfc"],
  },
  {
    term: "Analytics",
    slug: "analytics",
    category: "Search and measurement",
    shortDefinition: "The collection and interpretation of defined data to answer questions about behavior, performance, and business decisions.",
    definition: "Analytics is broader than one product. It includes the measurement plan, data collection, definitions, quality controls, privacy choices, reporting, interpretation, and decisions made from the evidence. Website analytics commonly use events, dimensions, metrics, and conversion definitions.",
    whyItMatters: "The useful system starts with a question and an action, then collects only the information needed to evaluate them.",
    commonMisunderstanding: "A dashboard is not automatically analytics, and more collected data does not guarantee a better decision.",
    relatedTermSlugs: ["google-analytics", "event", "conversion", "api"],
    sourceIds: ["google-analytics", "google-search-console"],
  },
  {
    term: "Metadata",
    slug: "metadata",
    category: "Search and measurement",
    shortDefinition: "Structured information describing a page or resource, including titles, descriptions, canonical references, and social-sharing fields.",
    definition: "Metadata describes content outside or alongside the main visible body. Website examples include the document title, meta description, canonical URL, robots directives, language, Open Graph fields, and structured data. Some fields influence presentation; none replace useful page content.",
    whyItMatters: "Accurate metadata helps browsers, search systems, social platforms, and internal tools understand which page exists and how it should be represented.",
    commonMisunderstanding: "A meta description is not a ranking guarantee and may not be used verbatim in a search result.",
    relatedTermSlugs: ["seo", "canonical-url", "structured-data", "indexing"],
    sourceIds: ["google-search-console", "mdn-web"],
  },
  {
    term: "Canonical URL",
    slug: "canonical-url",
    aliases: ["canonical"],
    category: "Search and measurement",
    shortDefinition: "The preferred URL identified for a page when the same or closely related content can be reached through multiple URLs.",
    definition: "A canonical reference helps search systems understand which URL the site considers primary among duplicates or near-duplicates. Canonicalization also depends on redirects, internal links, sitemaps, status codes, and consistent production URLs.",
    whyItMatters: "Migrations and platform parameters can create multiple addresses for similar content, fragmenting signals and complicating reporting.",
    commonMisunderstanding: "A canonical tag is a signal, not an access control or unconditional command, and it does not repair unrelated or low-quality duplicate pages by itself.",
    relatedTermSlugs: ["url", "redirect", "xml-sitemap", "indexing"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "Structured data",
    slug: "structured-data",
    aliases: ["schema markup", "Schema.org"],
    category: "Search and measurement",
    shortDefinition: "Machine-readable fields that describe visible entities and content using an agreed vocabulary and supported format.",
    definition: "Structured data can identify an organization, breadcrumb trail, service, article, product, event, or other supported entity using explicit properties. It should represent truthful content visitors can also find on the page.",
    whyItMatters: "It can reduce ambiguity for search and other systems and support eligible enhanced presentations when platform requirements are met.",
    commonMisunderstanding: "Adding schema markup does not guarantee a rich result, ranking, or inclusion, and invented fields can create policy and trust problems.",
    relatedTermSlugs: ["metadata", "seo", "json"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "CMS",
    slug: "cms",
    aliases: ["content management system"],
    category: "Web foundations",
    shortDefinition: "Software used to create, organize, edit, and publish website content without manually changing every delivered file.",
    definition: "A content management system stores or structures content and provides an editing workflow. Some CMS platforms render pages dynamically; others feed a static-site build. The editing experience, content portability, permissions, maintenance, plugins, and hosting model vary widely.",
    whyItMatters: "The right CMS depends on who edits, how often, what approval is needed, and whether the content can be exported cleanly.",
    commonMisunderstanding: "Every website does not need a traditional CMS, and choosing one does not remove content governance or maintenance work.",
    relatedTermSlugs: ["static-site", "hosting", "deployment"],
    sourceIds: ["mdn-server"],
  },
  {
    term: "Cache",
    slug: "cache",
    aliases: ["caching"],
    category: "Web foundations",
    shortDefinition: "A stored reusable copy that can answer a request faster than recreating or retrieving the original resource again.",
    definition: "Browsers, CDNs, servers, and applications can cache files or responses. Cache rules determine how long a copy remains fresh, when it must be revalidated, and how a new deployment replaces or bypasses the old version.",
    whyItMatters: "Caching can improve speed and reduce server work, but it can also make a correct update appear missing until the relevant copy expires or is invalidated.",
    commonMisunderstanding: "“Clear the cache” is not one universal action; several independent caches may exist between source and visitor.",
    relatedTermSlugs: ["cdn", "browser", "deployment", "http"],
    sourceIds: ["mdn-http", "cloudflare-pages-limits"],
  },
  {
    term: "Website clarity",
    slug: "website-clarity",
    aliases: ["clarity"],
    category: "Web foundations",
    shortDefinition: "How quickly a visitor can understand what a business offers, who it serves, why it matters, and what to do next.",
    definition: "Website clarity comes from a legible offer, useful hierarchy, specific language, appropriate detail, and an obvious next step. It is evaluated from the visitor's point of view rather than by how familiar the site feels to the business that owns it.",
    whyItMatters: "Confusion adds friction before a visitor can compare the offer, decide whether the business fits, or take a useful next step.",
    commonMisunderstanding: "Clarity does not require making every page short or visually plain. Complex services may need substantial explanation; the structure should make that detail easier to navigate.",
    relatedTermSlugs: ["search-intent", "call-to-action", "responsive-design"],
    sourceIds: [],
  },
  {
    term: "Trust signal",
    slug: "trust-signal",
    aliases: ["trust signals"],
    category: "Search and measurement",
    shortDefinition: "A specific, checkable detail that reduces uncertainty about a business, its offer, its process, or the next step.",
    definition: "Trust signals can include clear ownership, consistent business facts, real project or product proof, transparent process, useful policies, responsive contact paths, verified credentials when relevant, and honest limits. The appropriate signals depend on the decision a customer is making.",
    whyItMatters: "Visitors often need enough evidence to judge whether the business is credible, suitable, and safe to contact before they will act.",
    commonMisunderstanding: "A badge, stock testimonial, or unsupported guarantee is not trustworthy merely because it looks official. The signal should be specific, relevant, and verifiable.",
    relatedTermSlugs: ["conversion", "call-to-action", "google-business-profile"],
    sourceIds: [],
  },
  {
    term: "Customer discovery",
    slug: "customer-discovery",
    aliases: ["discovery"],
    category: "Search and measurement",
    shortDefinition: "The paths customers use to find and begin evaluating a business, service, product, or answer.",
    definition: "Customer discovery may happen through search, maps, referrals, marketplaces, directories, social channels, media, links, or direct navigation. The useful mix depends on the market and on how customers actually research the decision.",
    whyItMatters: "A website and visibility plan should support the channels and questions that bring suitable customers into the decision process.",
    commonMisunderstanding: "Discovery is not synonymous with ranking for one keyword. A customer may encounter and compare a business across several surfaces before visiting the site or making contact.",
    relatedTermSlugs: ["search-intent", "seo", "local-seo", "google-business-profile"],
    sourceIds: [],
  },
  {
    term: "Customer action",
    slug: "customer-action",
    aliases: ["customer actions", "valuable customer action", "qualified customer action"],
    category: "Search and measurement",
    shortDefinition: "A useful next step a customer takes, such as calling, requesting a quote, booking, visiting, buying, or making a qualified inquiry.",
    definition: "A customer action is defined by the business outcome and the visitor's decision stage. It may be a direct sale or inquiry, but it can also be a meaningful intermediate step such as viewing a high-value service, checking availability, comparing options, or continuing to a relevant guide.",
    whyItMatters: "Naming the valuable action helps connect website structure, calls to action, measurement, and improvement work to something the business can use.",
    commonMisunderstanding: "Not every click is a valuable action, and an analytics event is not automatically a lead or sale. The business still needs to interpret quality and outcome.",
    relatedTermSlugs: ["call-to-action", "conversion", "event", "analytics"],
    sourceIds: [],
  },
  {
    term: "Call to action",
    slug: "call-to-action",
    aliases: ["CTA"],
    category: "Search and measurement",
    shortDefinition: "A clear invitation that tells a visitor which useful action they can take next.",
    definition: "A call to action can invite a visitor to call, request an estimate, book, buy, visit, compare, download, or continue learning. The label, destination, timing, prominence, and surrounding proof should match the visitor's decision stage.",
    whyItMatters: "A strong page can still fail when the next step is hidden, vague, unavailable, or mismatched to the offer.",
    commonMisunderstanding: "Changing button color alone is not conversion strategy; the offer, trust, page structure, form, response process, and business capacity also matter.",
    relatedTermSlugs: ["conversion", "event", "analytics"],
    sourceIds: ["google-analytics"],
  },
  {
    term: "Search intent",
    slug: "search-intent",
    category: "Search and measurement",
    shortDefinition: "The underlying task or decision a person is trying to complete when they enter a search query.",
    definition: "Search intent can involve learning, comparing, locating, buying, booking, troubleshooting, or navigating to a known entity. A useful page matches the real task with appropriate depth and a sensible next action.",
    whyItMatters: "A page can mention the right phrase and still fail if it answers the wrong question or pushes a sale before the visitor can evaluate the decision.",
    commonMisunderstanding: "Intent is an evidence-based interpretation, not a permanent label attached to every occurrence of a keyword.",
    relatedTermSlugs: ["seo", "conversion", "call-to-action"],
    sourceIds: ["google-search-console"],
  },
  {
    term: "Keyword",
    slug: "keyword",
    aliases: ["search term"],
    category: "Search and measurement",
    shortDefinition: "A word or phrase used to describe a search topic; actual search queries provide the more precise observed wording.",
    definition: "SEO work often groups related queries into keyword themes. The useful goal is to understand the customer language, intent, service, and page needed—not to repeat an exact phrase mechanically throughout the copy.",
    whyItMatters: "Keyword research can reveal demand language and content gaps when combined with market, business, and first-party evidence.",
    commonMisunderstanding: "A high-volume keyword is not automatically valuable, attainable, local, relevant, or likely to produce a qualified lead.",
    relatedTermSlugs: ["seo", "search-intent", "google-search-console"],
    sourceIds: ["google-search-console"],
  },
];

export const glossaryBySlug = new Map(
  glossaryEntries.map((entry) => [entry.slug, entry]),
);

export const glossaryAliasIndex = new Map(
  glossaryEntries.flatMap((entry) =>
    [entry.term, ...(entry.aliases ?? [])].map((label) => [
      label.toLocaleLowerCase(),
      entry,
    ] as const),
  ),
);

export const glossaryAliasPattern = [...glossaryAliasIndex.keys()]
  .sort((left, right) => right.length - left.length)
  .map((label) => label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
  .join("|");

export const commonGlossarySlugs = [
  "seo",
  "analytics",
  "conversion",
  "client",
  "hosting",
  "local-seo",
  "call-to-action",
  "domain-name",
  "metadata",
  "url",
  "technical-seo",
  "dns",
];
