export const operatingCycle = [
  {
    id: "diagnose",
    number: "01",
    title: "Diagnose",
    body: "Understand the business, customer, market, website, systems, constraints, and valuable next action before prescribing work.",
    href: "/services/research-audits-strategy/",
    linkLabel: "Explore diagnosis and research",
  },
  {
    id: "prioritize",
    number: "02",
    title: "Prioritize",
    body: "Rank the possible work by business value, evidence, confidence, effort, risk, and the ability to measure it.",
    href: "/services/research-audits-strategy/",
    linkLabel: "See how priorities are chosen",
  },
  {
    id: "engineer",
    number: "03",
    title: "Engineer",
    body: "Design, repair, migrate, write, configure, or automate the smallest useful system with a clear scope.",
    href: "/services/",
    linkLabel: "Explore what Boho engineers",
  },
  {
    id: "deploy",
    number: "04",
    title: "Deploy",
    body: "Move the agreed change into its real environment with ownership, rollback, and verification recorded.",
    href: "/services/provider-rescue/",
    linkLabel: "See how deployment risk is handled",
  },
  {
    id: "measure",
    number: "05",
    title: "Measure",
    body: "Review the signals tied to the intended outcome, document uncertainty, and separate evidence from decoration.",
    href: "/services/research-audits-strategy/",
    linkLabel: "Explore measurement and analytics",
  },
  {
    id: "improve",
    number: "06",
    title: "Improve",
    body: "Keep what has a case, change what does not, document the decision, and begin the next useful cycle.",
    href: "/services/ongoing-seo/",
    linkLabel: "See how ongoing improvement works",
  },
] as const;
